
<?php 
require_once './templates/header.phtml';
  if ($error) {
    echo $error;
  }?>
<div class="container d-flex align-items-center justify-content-center" style="min-height: 80vh;">
        <div class="col-md-4">
          <h3 class="text-center mb-2">Inicio de Sesión</h3>

          <form action="logueo" method="POST" class="login-form"> 
            <div class="mb-3">
              <label for="usuario" class="form-label">Usuario</label>
              <input type="text" class="form-control" id="usuario" name="usuario" placeholder="Ingrese usuario" >
            </div>
            <div class="mb-3">
              <label for="password" class="form-label">Contraseña</label>
              <input type="password" class="form-control" id="contraseña" name="contraseña" placeholder="********" >
            </div>
            <div class="d-grid">
              <button type="submit" class="btn btn-primary btn-custom">Ingresar</button>
            </div>
          </form>
        </div>
      </div>
</body>
</html>
